# Generated by Django 3.1.2 on 2020-11-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='data',
            new_name='date',
        ),
    ]
