# Generated by Django 3.1.2 on 2020-11-08 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201108_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
