# Generated by Django 3.1.2 on 2020-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20201108_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
